[package]
name = "ports"
version = "0.1.0"
authors = ["Till Wegmueller <toasterson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
clap = "~3.0.0-beta.2"
specfile = {path = "../specfile"}
shellexpand = "2.1.0"
url = { version = "2.1.1", features = ["serde"]}
reqwest = { version = "0.11", features = ["blocking"] }
which = "4.1.0"